# Generated by Django 4.0 on 2021-12-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=200, null=True, verbose_name='By')),
                ('descendants', models.PositiveIntegerField(default=0)),
                ('itemID', models.PositiveBigIntegerField(unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('time', models.PositiveBigIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('dead', models.BooleanField(blank=True, default=False, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('parent', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
