# Generated by Django 4.0 on 2021-12-17 11:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='APICreated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='kids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='by',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='By'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
