# Generated by Django 4.0 on 2021-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='itemID',
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
